Added method for getting clipboard content
selenide/selenide-selenoid pull request #6
Opened 2021-02-15 12:12 UTC by dbudim

2021-02-20 21:50 UTC, asolntsev requested changes
@dbudim Thank you! A couple of questions: 
1. Do you really need to use `OkHttpClient`? `SelenoidClient` already has method `readToString` for performing GET requests.
2. How it would be easier for users to use clipboard?
Current syntax `new ClipboardSelenoid(...).get();` is ok, but probably it would be even better to have methods like `getClipboard`, `setClipboard` or even `clipboard.shouldHave(text(..))` in Selenide, and override them in `selenide-selenoid`?

2021-02-22 06:23 UTC, dbudim commented
> @dbudim Thank you! A couple of questions:
> 
> 1. Do you really need to use `OkHttpClient`? `SelenoidClient` already has method `readToString` for performing GET requests.
> 2. How it would be easier for users to use clipboard?
>    Current syntax `new ClipboardSelenoid(...).get();` is ok, but probably it would be even better to have methods like `getClipboard`, `setClipboard` or even `clipboard.shouldHave(text(..))` in Selenide, and override them in `selenide-selenoid`?

@asolntsev 
OkHttpClient isn't really needed, i just prefer it in using. I'll change it to existed method )

About condition i've commented in PR to main repo, think it's cool idea)

2021-03-10 22:35 UTC, asolntsev approved these changes

2021-03-10 22:36 UTC, asolntsev requested changes
I would move GET/POST requests to class `org.selenide.selenoid.SelenoidClient`.

2021-03-11 21:04 UTC, merged